### ISSUE TITLE
quartz/go_process.rb:104:in `cleanup': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by rebyn** [DavidHuie/quartz#11]
Running the example [here](https://github.com/DavidHuie/quartz/tree/master/examples) I came across an error:

```
$ ruby lookup_dns.rb
quartz-0.2.4/lib/quartz/go_process.rb:104:in `cleanup': undefined method `each' for nil:NilClass (NoMethodError)
	from quartz-0.2.4/lib/quartz/go_process.rb:110:in `block in <top (required)>'
lib/quartz/validations.rb:8:in `check_for_go': Go not installed (RuntimeError)
	from quartz-0.2.4/lib/quartz.rb:13:in `<top (required)>'
	from /.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from lookup_dns.rb:1:in `<main>'
```

**Comment by DavidHuie** [comment]
It looks like everything's good here. For next time, just run `go get github.com/DavidHuie/quartz` and run the Ruby code from within the `GOPATH`.
